"""
HAIGC Mask Node Suite
专业的遮罩处理节点套件
"""

# 导入所有保留的节点
from .mask_selector_node import NODE_CLASS_MAPPINGS as SELECTOR_NODE_MAPPINGS
from .mask_selector_node import NODE_DISPLAY_NAME_MAPPINGS as SELECTOR_DISPLAY_MAPPINGS

from .mask_resize_node import NODE_CLASS_MAPPINGS as RESIZE_NODE_MAPPINGS
from .mask_resize_node import NODE_DISPLAY_NAME_MAPPINGS as RESIZE_DISPLAY_MAPPINGS

from .mask_transform_node import NODE_CLASS_MAPPINGS as TRANSFORM_NODE_MAPPINGS
from .mask_transform_node import NODE_DISPLAY_NAME_MAPPINGS as TRANSFORM_DISPLAY_MAPPINGS

from .mask_generator_node import NODE_CLASS_MAPPINGS as GENERATOR_NODE_MAPPINGS
from .mask_generator_node import NODE_DISPLAY_NAME_MAPPINGS as GENERATOR_DISPLAY_MAPPINGS

from .mask_compare_node import NODE_CLASS_MAPPINGS as COMPARE_NODE_MAPPINGS
from .mask_compare_node import NODE_DISPLAY_NAME_MAPPINGS as COMPARE_DISPLAY_MAPPINGS

# 合并所有节点映射
NODE_CLASS_MAPPINGS = {
    **SELECTOR_NODE_MAPPINGS,
    **RESIZE_NODE_MAPPINGS,
    **TRANSFORM_NODE_MAPPINGS,
    **GENERATOR_NODE_MAPPINGS,
    **COMPARE_NODE_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **SELECTOR_DISPLAY_MAPPINGS,
    **RESIZE_DISPLAY_MAPPINGS,
    **TRANSFORM_DISPLAY_MAPPINGS,
    **GENERATOR_DISPLAY_MAPPINGS,
    **COMPARE_DISPLAY_MAPPINGS,
}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
