name: Publish to Comfy Registry

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
    paths:
      - "pyproject.toml"

jobs:
  publish-node:
    name: Publish HAIGC Mask Nodes to Registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      
      - name: Publish Custom Node to Comfy Registry
        uses: Comfy-Org/publish-node-action@main
        with:
          ## 在 GitHub 仓库的 Settings -> Secrets and variables -> Actions 中添加
          ## Secret 名称: COMFY_REGISTRY_TOKEN
          ## Secret 值: 从 Comfy Registry 获取的 Personal Access Token
          personal_access_token: ${{ secrets.COMFY_REGISTRY_TOKEN }}

